# Generated by Django 2.2.5 on 2020-11-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201111_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instanat_book',
            new_name='instant_book',
        ),
    ]
