# Generated by Django 2.2.5 on 2020-11-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201112_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facitilities',
            new_name='facilities',
        ),
    ]
