# Generated by Django 2.2.5 on 2020-11-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201113_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cleanlines',
            new_name='cleanliness',
        ),
    ]
